
/* generated by: ControllerGenerator Wed May 18 15:20:45 CEST 2016 */
package com.littleworld.todo.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Card {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    int id;

    String text;
    String kleur;

    public Card() {}

    public String getKleur() {
        return kleur;
    }

    public void setKleur(String kleur) {
        this.kleur = kleur;
    }

    public Card(int id, String text, String kleur) {
        this.id = id;
        this.text = text;
        this.kleur = kleur;
    }
    public int getId() { return id; }
    public void setId(int id)  { this.id = id; }
    public String getText() { return text; }
    public void setText(String task)  { this.text = task; }
    @Override
    public String toString() {
        return "[Card: [" + "id: " + id + ", " + "text: " + text + "kleur: " + kleur + "]";
    }
}

